application: webreflinks
version: 4
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: webreflinks.application
- url: /list
  script: webreflinks.list
- url: /api
  script: webreflinks.api